package com.io.sdchain.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.io.sdchain.bean.MsgBean;

import com.io.sdchain.greendao.MsgBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig msgBeanDaoConfig;

    private final MsgBeanDao msgBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        msgBeanDaoConfig = daoConfigMap.get(MsgBeanDao.class).clone();
        msgBeanDaoConfig.initIdentityScope(type);

        msgBeanDao = new MsgBeanDao(msgBeanDaoConfig, this);

        registerDao(MsgBean.class, msgBeanDao);
    }
    
    public void clear() {
        msgBeanDaoConfig.clearIdentityScope();
    }

    public MsgBeanDao getMsgBeanDao() {
        return msgBeanDao;
    }

}
